version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sunday
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /home/ubuntu/scripts/sunday-after-install.sh
      timeout: 300
      runas: ubuntu
