version: 0.2
os: linux

files:
  - source: /
    destination: /home/ec2-user/sunday
    overwrite: yes

permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  AppliiationStart:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ec2-user
