name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 16 & Pnpm 8
        uses: actions/setup-node@v3
        with:
          node-version: 16
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Run tests
        run: pnpm test

      - name: Install Railway
        run: pnpm add -g @railway/cli

      - name: Remove the most recent deployment
        run: railway down

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
