name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Pnpm 8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        env:
          EVERNOTE_TOKEN: ${{ secrets.TEST_EVERNOTE_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TEST_TELEGRAM_BOT_TOKEN }}

      - name: Install Railway
        run: pnpm add -g @railway/cli

      - name: Deploy
        run: railway up --service sunday-ai
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
