name: 'test'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo EVERNOTE_TOKEN=${{ secrets.EVERNOTE_TOKEN }} >> .env
          echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> .env

      - name: install dependencies
        run: pnpm install

      # - name: run tests
      #   run: pnpm test
